apiVersion: v1
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Nodejs Runtime Image
    labels:
      shared: "true"
    creationTimestamp: null
    generation: 0
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: null
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 0
    labels: null
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentConfig: ${NAME}${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations: null
        creationTimestamp: null
        labels:
          deploymentConfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: lucy-db
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}${SUFFIX}
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}${SUFFIX}
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${NAME}${SUFFIX}
          - name: DB_PORT
            value: "5432"
          - name: APP_CERTIFICATE_URL
            value: "https://sso.pathfinder.gov.bc.ca/auth/realms/dfmlcg7z/protocol/openid-connect/certs"
          image: " "
          imagePullPolicy: Always
          name: api
          ports:
          - containerPort: 3001
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/app-root/app
            name: lucy-api-test-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: lucy-api-test-1
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - api
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  stringData:
    database-name: ""
    database-password: ""
    database-user: ""
  kind: Secret
  metadata:
    annotations:
      as-copy-of: lucy-db
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    creationTimestamp: null
    labels: {}
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: 3001-tcp
      port: 3001
      protocol: TCP
      targetPort: 3001
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations: {}
    creationTimestamp: null
    labels: {}
    name: ${NAME}${SUFFIX}
  spec:
    host: ${HOST}
    port:
      targetPort: 3001-tcp
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None
  status:
    ingress: null
kind: Template
metadata:
  resourceVersion: ""
  selfLink: ""
parameters:
- name: NAME
  value: lucy-api
- name: SUFFIX
  value: "-dev"
- name: VERSION
  value: "1.0.0"
- name: HOST