# Clean out the deployment artifacts when a PR is closed, without a merge.
# This clean out gets rid of the PR artifacts in Dev and in Tools.
name: Clean out Dev from closed PR Artifacts
on:
  pull_request:
    types: [closed]
    branches:
      - dev
jobs:
  clean:
    name: Clean Deployment Artifacts for App, API, and API-MOBILE in Dev and Tools environment
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged != true && github.base_ref == 'dev'  }}
    env:
      BUILD_ID: ${{ github.event.number }}
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v1

      # Install Node - for `node` and `npm` commands
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16

      # Log in to OpenShift.
      - name: Log in to OpenShift
        run: oc login https://console.pathfinder.gov.bc.ca:8443 --token=${{ secrets.TOOLS_SA_TOKEN }}

      # Clean the api deployment artifacts
      - name: Clean API Deployment
        working-directory: "./api/.pipeline/"
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev

      # Clean the api-mobile deployment artifacts
      - name: Clean API Mobile Deployment
        working-directory: "./api-mobile/.pipeline/"
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev

      # Clean the app deployment artifacts
      - name: Clean APP Deployment
        working-directory: "./app/.pipeline/"
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev
