# Test Deploy On OpensShift
name: Static Deploy on OpensShift

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev
      - prod
jobs:
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Vars
        run: |
          printenv
          echo ${{ github.base_ref }}
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
    #end steps
  #end checkEnv
# --